#!/bin/bash -ex
# enter the directory where the build script is located
cd "${0%/*}"

# some useful variables
SRC_DIR="$(pwd)/../../"
CURRENT_DISTRO=$(basename $(pwd))
BUILD_IMAGE="docker-rpm-builder-${CURRENT_DISTRO}-build"
TEST_IMAGE="docker-rpm-builder-${CURRENT_DISTRO}-test"

docker build --pull -t ${BUILD_IMAGE} build-image

rm -rf out

docker run --env "BUILD_NUMBER=${BUILD_NUMBER:-0}" --env "GIT_COMMIT=${GIT_COMMIT:-asd}" --env-file ../env.list --rm -v $(pwd)/build-inside:/build-inside:ro -v ${SRC_DIR}:/source:ro -v $(pwd)/out:/out -w /build-inside ${BUILD_IMAGE} /build-inside/build-package

trap 'vagrant destroy --force' EXIT
vagrant up
vagrant ssh -c "sudo /home/vagrant/sync/test-inside/test"

#docker build --pull -t ${TEST_IMAGE} test-image

#rm -rf test-logs

#docker run --env-file ../env.list --rm -v ${HOME}/.docker/machine/machines/default:/root/.docker:ro -v $(pwd)/test-inside:/test-inside:ro -v $(pwd)/out:/out:ro -v $(pwd)/test-logs:/test-logs -w /test-inside ${TEST_IMAGE} /test-inside/test || { echo "ERROR: the test phase failed." ; exit 1 ; }
echo "Test phase succeeded."
