#!/bin/bash -ex
cat > /etc/apt/sources.list.d/docker.list <<EOF
deb https://apt.dockerproject.org/repo ubuntu-trusty main
EOF

curl https://apt.dockerproject.org/gpg | apt-key add -
apt-get update
dpkg -i /home/vagrant/sync/out/*.deb || /bin/true
apt-get -f install

usermod -a -G docker vagrant || /bin/true
service docker start || /bin/true

docker-rpm-builder selftest
