#!/bin/bash -ex
# enter the directory where the build script is located
cd "${0%/*}"

# some useful variables
SRC_DIR="$(pwd)/../../"
CURRENT_DISTRO=$(basename $(pwd))
BUILD_IMAGE="docker-rpm-builder-${CURRENT_DISTRO}-build"

docker build --pull -t ${BUILD_IMAGE} build-image

#rm -rf out

#docker run --env "BUILD_NUMBER=${BUILD_NUMBER:-0}" --env "GIT_COMMIT=${GIT_COMMIT:-asd}" --env-file ../env.list --rm -v $(pwd)/build-inside:/build-inside:ro -v ${SRC_DIR}:/source:ro -v $(pwd)/out:/out -w /build-inside ${BUILD_IMAGE} /build-inside/build-package

trap 'vagrant destroy --force' EXIT
vagrant up

echo "***** ${CURRENT_DISTRO} Starting test phase  (stable)."
vagrant ssh -c 'sudo /home/vagrant/sync/test-inside/test'
vagrant destroy --force
echo "***** ${CURRENT_DISTRO} Test phase succeeded (stable)."
echo
vagrant up
echo "***** ${CURRENT_DISTRO} Starting test phase  (rc)"
vagrant ssh -c 'sudo /home/vagrant/sync/test-inside-rc/test'
echo "${CURRENT_DISTRO} Test phase succeeded (rc)."
