#!/bin/bash -ex
cat > /etc/yum.repos.d/docker.repo <<EOF
[docker]
name=docker
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

yum -y install "docker-engine-1.8.3"

yum -y install /home/vagrant/sync/out/*.rpm

usermod -a -G docker vagrant || /bin/true
service docker start || /bin/true

docker-rpm-builder selftest --full
