#!/bin/bash
set -ex
# let git path be chosen if we want to use a different version that's not in the path
GIT=${GIT:-git}

# always recreate prodenv
rm -rf prodenv
virtualenv-2.7 prodenv
sed -i -e "s/dev0//g" version.txt
RELEASE_NUMBER="$(cat version.txt)"
prodenv/bin/pip install .
prodenv/bin/pip freeze > requirements.txt
prodenv/bin/pip install wheel
${GIT} add version.txt requirements.txt
${GIT} commit version.txt requirements.txt -m "Prepare for release ${RELEASE_NUMBER}"
${GIT} tag ${RELEASE_NUMBER} -m "Release tag"
prodenv/bin/python setup.py bdist_wheel sdist register upload
