#!/bin/bash -ex
apt-get update 
apt-get -y install apt-transport-https curl

cat > /etc/apt/sources.list.d/docker.list <<EOF
deb https://apt.dockerproject.org/repo debian-jessie main
EOF

rm -f /tmp/test.exit
EXIT_CODE=1
trap 'echo ${EXIT_CODE} > /tmp/test.exit' EXIT
curl https://apt.dockerproject.org/gpg | apt-key add -
apt-get update

dpkg -i /home/vagrant/sync/out/*.deb || /bin/true
apt-get -f -y install

service docker start || /bin/true

docker-rpm-builder selftest --full
EXIT_CODE=$?
exit ${EXIT_CODE}
